## Python Programming Language Assignment

#### **Instructions**:
- Solve each problem using Python. Ensure that your code is efficient and handles exceptions where applicable.
- Solutions should be submitted in a well-structured `.py` file or Jupyter Notebook with clear comments.
- You are encouraged to research, but the code must be your own.


### **Problem 1: Numerical Operations and String Manipulation**  
Write a Python program that:
1. Accepts two numbers (int or float) as input and performs the following:
   - **Exponentiation** using both `**` and `pow()`.
   - Calculates the **modulus** of both numbers.
   - Computes the **floor** and **ceiling** of the division of the two numbers using the `math` module.
2. Asks the user to input a string. The program should:
   - Count the frequency of each character using a dictionary.
   - Identify the character that occurs the most and print it.
   - Convert the string into an acronym by taking the first letter of each word (handle multi-word strings).

In [6]:
#importing math module
import math

class Math :

    # Creating power function
    def power(self,a,b):
        return a**b

    #Creating modulus function
    def modulus(self,a,b):
        return a%b

    #Creating floor_and_ceiling function to find both floor and ceil at the same time
    def floor_and_ceiling(self,a,b):
        print(f"floor of a:{math.floor(a)}, floor of b : {math.floor(b)}")
        print(f"ceiling of a:{math.ceil(a)} ceiling of b : {math.ceil(b)}")

math_instance = Math()

print(math_instance.power(2,3))
print(math_instance.modulus(6,87))
math_instance.floor_and_ceiling(3.23,64.23)


8
6
floor of a:3, floor of b : 64
ceiling of a:4 ceiling of b : 65


In [18]:
# Taking string input from the user.
input_str = input("Enter the string: ")

# Creating a dictionary of frequency and the letter of the given string
frequency_count = { i : input_str.count(i) for i in input_str}
print(frequency_count)

print('Highest frequecy : ', max(frequency_count))

def find_most_frequent_character(frequency_dict):
    # Find the character with the maximum frequency
    most_frequent_char = max(frequency_dict, key=frequency_dict.get)
    return most_frequent_char, frequency_dict[most_frequent_char]

most_frequent_char, frequency = find_most_frequent_character(frequency_count)
print(f"\nThe character that occurs the most is '{most_frequent_char}' with a frequency of {frequency}.")

words = input_str.split()
acronym = ''.join(word[0].upper() for word in words)
print("Acronym: ",acronym)

Enter the string:  hello world


{'h': 1, 'e': 1, 'l': 3, 'o': 2, ' ': 1, 'w': 1, 'r': 1, 'd': 1}

The character that occurs the most is 'l' with a frequency of 3.
Acronym:  HW


### **Problem 2: Nested Data Structures with Lists and Tuples**  
You are given a nested list of tuples representing product sales data. Each tuple contains the product name, sales quantity, and price per unit:
```python
sales_data = [('Laptop', 30, 1500), ('Tablet', 50, 600), ('Smartphone', 120, 800)]
```
Write a program that:
1. Calculates the **total revenue** for each product and stores it in a new list.
2. Sorts the list of tuples by total revenue in **descending order**.
3. Converts this list into a **tuple of tuples** and performs the following:
   - Find the product with the **maximum total revenue**.
   - Extract a **sub-tuple** containing the top 2 products by revenue.

In [2]:
sales_data = [('Laptop', 30, 1500), ('Tablet', 50, 600), ('Smartphone', 120, 800)]

total_revenue = [ q*p for s,q,p in sales_data]
print(f"Total revenue: {total_revenue}")
descending_total_revenue = sorted(total_revenue, reverse = True)
print(f"Descending order total revenue :{descending_total_revenue}")

# Converting lsit in tuple
tuple_total_revenue = tuple(sales_data)
print(tuple_total_revenue)
type(tuple_total_revenue)

print("Maximum of total revenue",max(q*p for s,q,p in tuple_total_revenue))

top_products = sorted(tuple_total_revenue, key=lambda x: x[1] * x[2], reverse = True)[:2]
print(top_products)

Total revenue: [45000, 30000, 96000]
Descending order total revenue :[96000, 45000, 30000]
(('Laptop', 30, 1500), ('Tablet', 50, 600), ('Smartphone', 120, 800))
Maximum of total revenue 96000
[('Smartphone', 120, 800), ('Laptop', 30, 1500)]


### **Problem 3: Set Operations with Unique Data and Optimization**  
You have two sets representing the IDs of users who logged into a system over two different weeks:
```python
week1 = {1001, 1002, 1003, 1004, 1005}
week2 = {1003, 1004, 1005, 1006, 1007}
```
Write a Python program that:
1. Identifies users who logged in during **both weeks** and stores them in a new set.
2. Computes the **symmetric difference** (users who logged in only in one of the weeks).
3. Optimizes set operations by handling cases where sets could be very large. Use `timeit` to compare the performance of your set operations.
4. Write an explanation of the performance differences you observe.

In [15]:
week1 = {1001, 1002, 1003, 1004, 1005}
week2 = {1003, 1004, 1005, 1006, 1007}

#new_log_set = set()

# for i in week1:
#     if i in week2:
#         new_log_set.add(i)
# print('users who logged in during both weeks are: ',new_log_set)
import timeit

intersection_set = week1.intersection(week2)
print('users who logged in during both weeks are: ',intersection_set)

sym_diff = week1.symmetric_difference(week2)
print(f"User who logged in only in one of the weeks: {sym_diff}")

# Measure time for intersection operation
intersection_time = timeit.timeit(lambda: week1.intersection(week2), number=10000)

# Measure time for symmetric difference operation
sym_diff_time = timeit.timeit(lambda: week1.symmetric_difference(week2), number=10000)

# Print time taken for each operation
print(f"Time for intersection: {intersection_time} seconds")
print(f"Time for symmetric difference: {sym_diff_time} seconds")

users who logged in during both weeks are:  {1003, 1004, 1005}
User who logged in only in one of the weeks: {1001, 1002, 1006, 1007}
Time for intersection: 0.002736712999876545 seconds
Time for symmetric difference: 0.0034691009998368827 seconds


### **Problem 4: Dictionary with Nested Structures and Data Aggregation**  
You have a dictionary representing the monthly sales data for a year, where each value is a dictionary with details about the sales for different categories:
```python
sales = {
    'January': {'Electronics': 5000, 'Clothing': 3000, 'Grocery': 2000},
    'February': {'Electronics': 6000, 'Clothing': 3500, 'Grocery': 2500},
    'March': {'Electronics': 5500, 'Clothing': 3200, 'Grocery': 2400}
}
```
Write a program that:
1. **Adds** a new category "Home Appliances" with random sales values for each month.
2. Calculates the **total sales** for each month and stores the result in a new dictionary.
3. Identifies the **best performing month** by total sales.
4. Extracts and prints the top **two categories** that contributed the most to the sales in the best performing month.

In [42]:
import random
sales = {
    'January': {'Electronics': 5000, 'Clothing': 3000, 'Grocery': 2000},
    'February': {'Electronics': 6000, 'Clothing': 3500, 'Grocery': 2500},
    'March': {'Electronics': 5500, 'Clothing': 3200, 'Grocery': 2400}
}


for months in sales:
    sales[months]['Home Appliances'] = random.randint(4000,11000)

print(sales)

total_sales = { month: sum(data.values())for month,data in sales.items()}
print('Total Sales: ',total_sales)

# Identify the best performing month by total sales
best_month = max(total_sales, key=total_sales.get)
best_sales = total_sales[best_month]

print(best_month,':',best_sales)

# Printing the top two categories that contributed the most to the sales in the best performing month.

top_categories = sorted(sales[best_month].items(),key = lambda x: x[1] ,reverse = True)[:2]
for category, value in top_categories:
    print(f"{category}: {value}")

{'January': {'Electronics': 5000, 'Clothing': 3000, 'Grocery': 2000, 'Home Appliances': 5473}, 'February': {'Electronics': 6000, 'Clothing': 3500, 'Grocery': 2500, 'Home Appliances': 9477}, 'March': {'Electronics': 5500, 'Clothing': 3200, 'Grocery': 2400, 'Home Appliances': 9649}}
Total Sales:  {'January': 15473, 'February': 21477, 'March': 20749}
February : 21477
Home Appliances: 9477
Electronics: 6000


### **Problem 5: Control Flow with Nested Loops and Complex Logic**  
Write a Python program that simulates a **number guessing game**:
1. The program should generate a random number between 1 and 100 and give the user 7 attempts to guess it.
2. After each wrong guess, the program should provide a hint whether the guess was too high or too low.
3. If the user fails to guess the number within the attempts, the program should reveal the number and ask if they would like to play again.
4. Implement **exception handling** to handle non-integer inputs and prompt the user to try again without counting the attempt.

In [7]:
## import random

random_number = random.randint(1,100)
i = 0
while i <=7:
    
    try :  
         if i == 7:
            
            print(f'You loose !!!!!! Correct number is {random_number}')
            break
             
         else: 
            guess = int(input(f" {i+1} Enter you guess: "))
            
            if random_number < guess:
                print(f"Your guess number ({guess}) is high")
        
            elif guess < random_number:
                print(f"Your guess number ({guess}) is low")
            
            if guess == random_number:
                print(f"Congratulations!!!!!!!!!!!! \nNumber : {guess} is a correct number")
                break
    
    except ValueError: 
        print("!!! Please enter only real number as a guess.!!!")
        continue
    
    i+=1

 1 Enter you guess:  50


Your guess number (50) is high


 2 Enter you guess:  30


Your guess number (30) is high


 3 Enter you guess:  20


Your guess number (20) is high


 4 Enter you guess:  10


Your guess number (10) is low


 5 Enter you guess:  17


Your guess number (17) is high


 6 Enter you guess:  12


Congratulations!!!!!!!!!!!! 
Number : 12 is a correct number


### **Problem 6: Functions with Memoization and Advanced Usage**  
Write a Python program that:
1. Implements a recursive function to calculate the **Nth Fibonacci number** but uses **memoization** to optimize repeated calculations. Use a dictionary to store already computed Fibonacci numbers.
2. Implements a lambda function that checks if a number is **prime**, and uses it to filter prime numbers from a list of random integers.
3. Uses the `reduce` function to find the **greatest common divisor (GCD)** of a list of integers.

In [3]:
def fibonacci(n, memo={}):
    # Check if the Fibonacci number is already calculated and in the memo
    if n in memo:
        return memo[n]
    
    # Base cases
    if n <= 1:
        return n

    # Recursive case with memoization
    memo[n] = fibonacci(n - 1, memo) + fibonacci(n - 2, memo)
    return memo[n]

# Example usage
n = 10
print(f"The {n}th Fibonacci number is {fibonacci(n)}")

The 10th Fibonacci number is 55


In [15]:
is_prime = lambda x: all(x % i != 0 for i in range(2, int(x**0.5) + 1)) and x > 1

is_prime(120)

False

In [4]:
from functools import reduce
from math import gcd

def gcd_of_list(numbers):
    return reduce(gcd, numbers)

# Example usage
numbers = [48, 64, 80, 96]
print(f"The GCD of the list is: {gcd_of_list(numbers)}")

The GCD of the list is: 16


### **Problem 7: OOP Concepts**  
Create a class `BankAccount` that:
1. Allows a user to create an account by providing a **name** and an initial **balance**.
2. Includes methods to **deposit**, **withdraw**, and **check balance**. The withdrawal should not allow an account to go negative.
3. Overloads the `+` operator to allow merging of two accounts (sum of their balances) and returns a new account.
4. Uses **Inheritance** to create a subclass `SavingsAccount` that adds an interest rate. Implement a method to calculate interest on the balance and update it accordingly.

In [24]:
class BankAccount:

    def __init__(self, name, balance = 0):
        self.name = name
        self.balance = balance
        
    def deposit(self, deposit=0):
        self.balance += deposit
        print(f'{deposit} amount has been credited in your account.')
        
    def withdraw(self, withdraw_amount):
        
        if self.balance < withdraw_amount:
            print('Insufficient Balance')
        else:
            self.balance -= withdraw_amount
            print(f'{withdraw_amount} amount has been debited from your account.')
        
    def checkBalance(self):
        return f' Total Balance : {self.balance} '
        
    def __add__(self,other):
        merged_account = BankAccount(f"{self.name} & {other.name}", self.balance + other.balance)
        return merged_account

    
class SavingsAccount(BankAccount):
    
    def __init__(self, name, balance=0 ):
        super().__init__(name, balance)  # Call the parent constructor
        self.interest_rate = 12  # Interest rate as a percentage (e.g., 2 for 2%)

    def calculate_interest(self):
        interest = (self.balance * self.interest_rate) / 100  # Calculate interest
        self.balance += interest  # Update balance
        print(f'Interest of {interest:.2f} has been added to your account.')
        
account1 = SavingsAccount('Namling Limbu', 200)
account1.deposit(500)
account1.withdraw(150)
account1.checkBalance()

account1.calculate_interest()


500 amount has been credited in your account.
150 amount has been debited from your account.
Interest of 66.00 has been added to your account.


### **Problem 8: File Handling with Data Processing**  
Write a Python program that:
1. Reads data from a text file containing multiple lines, where each line contains a name and a score (e.g., `John, 89`).
2. Stores the data in a dictionary and sorts the dictionary by score.
3. Writes the sorted data back into a new file, where the highest scores appear first.
4. The program should handle potential file I/O errors using appropriate exception handling techniques.


In [2]:
name_and_score = {}
with open('Nameandscore.txt', 'r') as f:
    data = f.read()
    print(data)
    f.seek(0)
    for line in f:
        name,score = line.strip().split(', ')
        name_and_score[name] = score
        
sorted_name_and_score = dict(sorted(name_and_score.items(), key = lambda item : item[1], reverse = True))
print(sorted_name_and_score)

Alice, 92
Mark, 78
Sarah, 85
David, 63
Emma, 90
Michael, 74
Olivia, 88
Daniel, 67
Sophia, 95
James, 82
Ava, 76
William, 89
Mia, 71
Ethan, 81
Emily, 93

{'Sophia': '95', 'Emily': '93', 'Alice': '92', 'Emma': '90', 'William': '89', 'Olivia': '88', 'Sarah': '85', 'James': '82', 'Ethan': '81', 'Mark': '78', 'Ava': '76', 'Michael': '74', 'Mia': '71', 'Daniel': '67', 'David': '63'}


In [7]:
try: 
    with open('SortedNameAndScore.txt', 'w') as f:
        f.write(str(sorted_name_and_score))

except Exception as e:
    print(e)
    
with open('SortedNameAndScore.txt', 'r') as f:
    data = f.read()
    print(data)

{'Sophia': '95', 'Emily': '93', 'Alice': '92', 'Emma': '90', 'William': '89', 'Olivia': '88', 'Sarah': '85', 'James': '82', 'Ethan': '81', 'Mark': '78', 'Ava': '76', 'Michael': '74', 'Mia': '71', 'Daniel': '67', 'David': '63'}


# Problem 9: Exception Handling and Debugging**  
Write a Python program that:
1. Takes a string input from the user and tries to convert it into an integer.
2. Raises a **custom exception** called `InvalidInputError` if the string contains non-numeric characters.
3. Ensures that the program continues to prompt for input until a valid integer is entered, and logs the errors into a text file for future reference.

In [13]:
class InvalidInputError(Exception):
    """Custom exception for invalid input."""
    pass

try: 
    message = input("Enter the string: ")
    int(message)  # Try to convert the input to an integer

except ValueError as e:
    # Create a custom exception
    error_message = "Value Error: The input is not convertible to an integer!"
  
    # Log the error to a file
    with open('error_log.txt', 'a+') as f:
        f.write(error_message + "\n")  # Write the error message to the log file
    
    # Raise the custom exception
    raise InvalidInputError(error_message) from e  # Raise custom exception


Enter the string:  Hello world


InvalidInputError: Value Error: The input is not convertible to an integer!

### **Problem 10: Numpy, Pandas, and Data Processing**  
1. Create a **3D numpy array** of random numbers. Compute the **mean** across each axis and the standard deviation of the entire array.
2. Using a Pandas DataFrame, simulate daily stock prices for 5 companies over a month (generate random data). Perform the following:
   - Calculate the **daily percentage change** in stock prices.
   - Identify the days with the highest and lowest percentage change for each stock.
   - Plot the **trend of stock prices** for any two selected companies on the same graph using Matplotlib.

In [22]:
import numpy as np
import random
array3 = np.random.randint(1,50, size = (3,3,3))
array3.shape

(3, 3, 3)

In [17]:
array3.mean()

np.float64(31.555555555555557)

In [24]:
# Compute the mean across each axis
mean_axis_0 = np.mean(array3, axis=0)
mean_axis_1 = np.mean(array3, axis=1)
mean_axis_2 = np.mean(array3, axis =2)
print(mean_axis_0)
print(mean_axis_1)
print(mean_axis_2)

std = np.std(array3)
print(f'Standard Deviation : {std}')

[[15.33333333 16.33333333 20.        ]
 [19.         12.66666667 15.        ]
 [19.         34.66666667 21.66666667]]
[[23.66666667 25.         17.        ]
 [11.66666667  7.33333333 12.66666667]
 [18.         31.33333333 27.        ]]
[[31.33333333  3.33333333 31.        ]
 [ 4.         14.         13.66666667]
 [16.33333333 29.33333333 30.66666667]]
Standard Deviation : 15.43880348178723
