## Elementwise Operator

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9], [10,11,12]])

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [4]:
a+b # np.add()

array([[ 8, 10, 12],
       [14, 16, 18]])

In [11]:
np.add(a,b)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [5]:
a-b # np.subtract()

array([[-6, -6, -6],
       [-6, -6, -6]])

In [12]:
np.subtract(a,b)

array([[-6, -6, -6],
       [-6, -6, -6]])

In [6]:
a*b # np.multiply()

array([[ 7, 16, 27],
       [40, 55, 72]])

In [14]:
np.multiply(a,b)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [7]:
a/b # np.divide()

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [15]:
np.divide(a,b)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [16]:
a%b # np.divmod()

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.divmod(a,b)

(array([[0, 0, 0],
        [0, 0, 0]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [18]:
a**b

array([[         1,        256,      19683],
       [   1048576,   48828125, 2176782336]])

In [19]:
np.sqrt(a) # square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

# Trognometric

In [23]:
new = 1/np.sin(a)
new

array([[ 1.18839511,  1.09975017,  7.0861674 ],
       [-1.32134871, -1.04283521, -3.57889955]])

In [22]:
1/np.tan(b)

array([[ 1.14751542, -0.14706506, -2.21084541],
       [ 1.54235105, -0.00442574, -1.57267341]])

# Rounding Operations

In [24]:
np.round(new)

array([[ 1.,  1.,  7.],
       [-1., -1., -4.]])

In [25]:
np.around(new,2)

array([[ 1.19,  1.1 ,  7.09],
       [-1.32, -1.04, -3.58]])

In [26]:
np.fix(new)

array([[ 1.,  1.,  7.],
       [-1., -1., -3.]])

In [27]:
np.floor(new)

array([[ 1.,  1.,  7.],
       [-2., -2., -4.]])

# Exponential Functions

In [28]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [29]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

# 2. Matrix Operations

In [40]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [17,8]])

print(a)
print(b)

[[1 2]
 [3 4]]
[[ 5  6]
 [17  8]]


In [41]:
np.dot(a,b)

array([[39, 22],
       [83, 50]])

In [42]:
np.transpose(b)

array([[ 5, 17],
       [ 6,  8]])

In [43]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [44]:
np.trace(a) # sum diagonally in 2D matrix

np.int64(5)

In [45]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [4]:
import numpy as np

In [13]:
a = np.array([[1,2], [3,4]])
np.dot(a, np.linalg.inv(a)).round()

array([[1., 0.],
       [0., 1.]])

In [10]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [14]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [15]:
import numpy as np

# Example square matrix
A = np.array([[4, -2],
              [1, 1]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[3. 2.]
Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


### Explanation
`Eigenvalues`: These are the scalars that indicate how much the eigenvectors are stretched or compressed during a transformation represented by the matrix 
𝐴
A.
`Eigenvectors`: These are the vectors that, when transformed by 
𝐴
A, do not change their direction. They can be thought of as the "axes" along which the transformation acts.