In [2]:
import numpy as np

In [3]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
arr.argmax(axis = 1) # gives the index of largest number in a row

array([4, 4])

In [5]:
arr.argmax(axis=0) # gives the index of largest number in a coloumn

array([1, 1, 1, 1, 1])

In [6]:
arr.argmax() # gives the index of largest number in array or matrix

np.int64(9)

In [7]:
arr.cumsum(axis = 1)

array([[ 1,  3,  6, 10, 15],
       [ 6, 13, 21, 30, 40]])

In [8]:
arr.cumsum(axis = 0)

array([[ 1,  2,  3,  4,  5],
       [ 7,  9, 11, 13, 15]])

In [9]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [19]:
arr1 = np.random.randint(low = 10, high = 50, size = (3,5) )
arr2 = np.random.randint(low = 10, high =50, size = (3,5))
print(arr1)
print(arr2)

[[27 14 47 15 17]
 [38 22 38 35 29]
 [27 49 28 26 25]]
[[37 17 45 16 19]
 [12 23 29 36 30]
 [46 28 28 39 45]]


In [20]:
result = np.vstack((arr1, arr2))
print(result)

[[27 14 47 15 17]
 [38 22 38 35 29]
 [27 49 28 26 25]
 [37 17 45 16 19]
 [12 23 29 36 30]
 [46 28 28 39 45]]


In [22]:
result2 = np.hstack((arr1,arr2))
result2

array([[27, 14, 47, 15, 17, 37, 17, 45, 16, 19],
       [38, 22, 38, 35, 29, 12, 23, 29, 36, 30],
       [27, 49, 28, 26, 25, 46, 28, 28, 39, 45]])