## type and type conversion

In [1]:
import numpy as np

In [2]:
a = np.array([1,22,5,3], dtype = np.int16)

In [3]:
a.dtype

dtype('int16')

In [12]:
arr11 = np.random.randint(low = 10,high = 50, size = (2,3),dtype = np.int16)
print(arr11)

[[17 12 12]
 [20 14 49]]


In [13]:
arr11.dtype

dtype('int16')

In [14]:
arr11.astype(np.float32)

array([[17., 12., 12.],
       [20., 14., 49.]], dtype=float32)

In [15]:
arr11.astype(np.bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [16]:
a

array([ 1, 22,  5,  3], dtype=int16)

In [17]:
bool_array = np.array([True, False, True, False], dtype=bool)
print(bool_array)

[ True False  True False]
