In [2]:
import numpy as np

array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [3]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [4]:
b = np.arange(1,5).reshape(2,2)
b

array([[1, 2],
       [3, 4]])

In [5]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.random.random((5,5))

array([[0.33622655, 0.40213202, 0.06952704, 0.68654613, 0.9679353 ],
       [0.26665133, 0.83309074, 0.77747471, 0.72925669, 0.92943949],
       [0.89486192, 0.5284999 , 0.4744927 , 0.76896823, 0.55255718],
       [0.84098153, 0.50916253, 0.6547741 , 0.42891065, 0.10220623],
       [0.42869196, 0.18171642, 0.10314633, 0.8243104 , 0.17998201]])

In [11]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.linspace(-10,10,10,dtype = int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [17]:
# ndim

a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a1.ndim

1

In [20]:
a2 = np.arange(10).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
a2.ndim

2

In [48]:
#reshape(collectionofvector,rows,colums)

a3 = np.arange(16).reshape(2,2,4)
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [50]:
a3.ndim

3

In [52]:
# shape

a3.shape

(2, 2, 4)

In [56]:
a2.shape
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Chaning datatype

In [55]:
a3.astype(np.int32)
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [69]:
arr = np.random.random(12).reshape(1,3,4)
arr

array([[[0.51804183, 0.88002087, 0.88933654, 0.91216003],
        [0.65165101, 0.68081802, 0.9249396 , 0.99332576],
        [0.07112083, 0.06347581, 0.17738848, 0.49327051]]])

## scalar operations

In [71]:
# arithmetic
(arr ** 2)

array([[[0.26836734, 0.77443674, 0.79091949, 0.83203593],
        [0.42464904, 0.46351318, 0.85551326, 0.98669607],
        [0.00505817, 0.00402918, 0.03146667, 0.2433158 ]]])

In [79]:
arr2 = np.arange(1,51).reshape(1,10,5)
arr2

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]]])

In [80]:
# Relational

arr2 > 5

array([[[False, False, False, False, False],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [84]:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

sum = array1+array2
sum

array([ 6,  8, 10, 12])

In [85]:
product = array1*array2
product

array([ 5, 12, 21, 32])

In [86]:
# scalar

scalar = array1 * 5
scalar

array([ 5, 10, 15, 20])

In [87]:
scalar.ndim

1

In [88]:
scalar.shape

(4,)

In [92]:
array = np.array([[1,2,3,4], [6,7,8,8]])
print(array.shape)
array

(2, 4)


array([[1, 2, 3, 4],
       [6, 7, 8, 8]])