In [2]:
import numpy as np

### 1. Create a NumPy Array
Create a 1D NumPy array with values from 0 to 9.

In [4]:

# list1 = [0,1,2,3,4,5,6,7,8,9]
# arr = np.array(list1)
# arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2. Array Shape and Reshaping
- Create a 2D array of shape (3, 3) filled with numbers from 1 to 9.
- Reshape the above array to shape (1, 9).

In [15]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr.shape

(3, 3)

In [17]:
arr.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## 3. Basic Array Operations
- Create two arrays: arr1 = [1, 2, 3] and arr2 = [4, 5, 6].
- Perform element-wise addition, subtraction, and multiplication on these arrays.

In [18]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr1+arr2

array([5, 7, 9])

In [19]:
arr1-arr2

array([-3, -3, -3])

In [20]:
arr1*arr2

array([ 4, 10, 18])

## 4. Array Indexing and Slicing
- Given the array arr = np.array([10, 20, 30, 40, 50]), extract the second to fourth elements (20, 30, 40).
- Create a 3x3 matrix and extract the second row and the third column.


In [22]:
arr = np.array([10,20,30,40,50])
arr[1:4]

array([20, 30, 40])

## 5. Statistical Functions
- Create an array of random integers between 1 and 100 of size (4, 4).
- Find the mean, sum, and standard deviation of the array.

In [24]:
array = np.random.randint(low = 1, high = 101, size = (4,4))
array

array([[ 8, 18, 75, 12],
       [54, 18, 94, 23],
       [50,  1, 51, 92],
       [24, 11, 29, 98]])

In [26]:
mean = np.mean(array)
total_sum = np.sum(array)
standard_deviation = np.std(array)

print(f'Mean : {mean}')
print(f"Sum: {total_sum}")
print(f"Standard Deviation: {standard_deviation}")

Mean : 41.125
Sum: 658
Standard Deviation: 32.02513661173048


## 6. Array Broadcasting
Create a 5x5 array of ones and multiply it by a 1D array [1, 2, 3, 4, 5] using broadcasting.

In [33]:
arr = np.ones((5,5))

D1array = np.array([1,2,3,4,5])

arr*D1array

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

## 7. Logical Operations
- Create an array of 10 random integers between 0 and 50.
- Print the array elements greater than 25.


In [44]:
array = np.random.randint(low=0, high=51, size=(1,10))
print(array>25)

[[ True False  True False False False False  True False  True]]


In [45]:
print(array[array>25])

[33 41 26 48]


## 8. Create Special Arrays
- Create a 4x4 identity matrix.
- Create an array filled with zeros of size 3x4.
- Create a 3x3 matrix filled with random values between 0 and 1.

In [52]:
arr_identity = np.identity(4)
arr_identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
arr_zeros = np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
zero_and_one = np.random.randint(low = 0, high = 2, size= (3,3))
zero_and_one

array([[0, 1, 1],
       [1, 0, 0],
       [0, 1, 0]])

## 9. Matrix Operations
- Create two 2x2 matrices and perform matrix multiplication.
- Find the transpose of a 3x3 matrix.

In [67]:
arr1 = np.random.randint(low = 0, high = 40, size = (2,2))
arr2 = np.random.randint(low = 0, high = 30, size = (2,2))
print(arr1)
print(arr2)
arr1*arr2

[[16  7]
 [14 28]]
[[16 26]
 [24  0]]


array([[256, 182],
       [336,   0]])

## 10. Advanced Slicing
- Given the array arr = np.arange(1, 17).reshape(4, 4), extract the following sub-arrays:
- First two rows and last two columns.
- Bottom-right 2x2 block.


In [68]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [69]:
arr[:2, -2:]

array([[3, 4],
       [7, 8]])