## Indexing-and-slicing

In [3]:
import numpy as np

In [4]:
np.random.randint(-10,10,10)

array([  7, -10,  -3,   7,  -6,   2,   3,   2,   7,   2])

In [5]:
# 1D Array -> Similar to List/Vector

array = np.array([1,5,3,7])

In [6]:
array[0]

np.int64(1)

In [7]:
print(array[0])

1


In [8]:
print(array[1::2])

[5 7]


In [9]:
# 2D -> Similar to matrix 
list2 = [[2,5,7,6], [4,9,11,23],[6,7,34,2],[12,5,2,8]]
array2 = np.array(list2)
array2

array([[ 2,  5,  7,  6],
       [ 4,  9, 11, 23],
       [ 6,  7, 34,  2],
       [12,  5,  2,  8]])

In [10]:
array2[0][2]

np.int64(7)

In [11]:
#array2[rows, columns]

array2[0:3, 0:3]

array([[ 2,  5,  7],
       [ 4,  9, 11],
       [ 6,  7, 34]])

In [12]:
array2[::2,]

array([[ 2,  5,  7,  6],
       [ 6,  7, 34,  2]])

In [13]:
array2.ndim

2

In [14]:
array2[::,]

array([[ 2,  5,  7,  6],
       [ 4,  9, 11, 23],
       [ 6,  7, 34,  2],
       [12,  5,  2,  8]])

In [15]:
array2.ndim

2

In [16]:
array2.shape

(4, 4)

In [17]:
random_array = np.random.randint(10,50, size = (2,3,4))

In [18]:
# Indexing 
random_array

array([[[35, 44, 48, 28],
        [40, 46, 20, 28],
        [34, 21, 34, 37]],

       [[17, 17, 24, 33],
        [42, 17, 13, 14],
        [33, 48, 44, 28]]])

In [19]:
print(random_array[0, 2, 2])

34


In [20]:
print(random_array[0, :2, :2])

[[35 44]
 [40 46]]


In [21]:
print(random_array[::2, :3, :4])

[[[35 44 48 28]
  [40 46 20 28]
  [34 21 34 37]]]


In [22]:
random_array

array([[[35, 44, 48, 28],
        [40, 46, 20, 28],
        [34, 21, 34, 37]],

       [[17, 17, 24, 33],
        [42, 17, 13, 14],
        [33, 48, 44, 28]]])

In [23]:
print(random_array[-1, :-2, :4])

[[17 17 24 33]]


In [24]:
random_array1 = np.random.randint(low = 10, high = 50, size = (10,16,8))

In [25]:
random_array1

array([[[30, 37, 10, ..., 41, 31, 22],
        [47, 13, 20, ..., 18, 25, 23],
        [20, 45, 19, ..., 33, 20, 43],
        ...,
        [34, 44, 25, ..., 14, 44, 29],
        [18, 39, 47, ..., 32, 12, 41],
        [19, 33, 11, ..., 36, 21, 33]],

       [[39, 10, 30, ..., 33, 16, 36],
        [32, 10, 24, ..., 40, 30, 15],
        [14, 36, 23, ..., 20, 14, 35],
        ...,
        [25, 48, 37, ..., 22, 43, 20],
        [33, 20, 46, ..., 17, 23, 23],
        [21, 34, 13, ..., 46, 20, 46]],

       [[12, 49, 32, ..., 36, 19, 33],
        [19, 25, 48, ..., 42, 46, 25],
        [49, 13, 31, ..., 21, 31, 26],
        ...,
        [48, 20, 16, ..., 42, 44, 25],
        [26, 13, 20, ..., 39, 34, 34],
        [33, 16, 38, ..., 17, 48, 48]],

       ...,

       [[13, 43, 15, ..., 44, 36, 30],
        [46, 29, 17, ..., 18, 10, 26],
        [48, 23, 34, ..., 27, 42, 34],
        ...,
        [13, 37, 28, ..., 45, 23, 15],
        [28, 44, 35, ..., 44, 22, 23],
        [16, 21, 37, ..., 14, 46

In [26]:
print(random_array1[4, :4, :9])

[[27 43 37 11 34 41 47 47]
 [18 33 19 30 11 20 44 40]
 [17 27 44 33 19 29 32 15]
 [39 10 10 10 36 32 43 47]]


In [27]:
print(random_array1[4, :4, -2: ])

[[47 47]
 [44 40]
 [32 15]
 [43 47]]


## Boolean or Mask Indexing

In [28]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [29]:
a == 4

array([[False, False],
       [False,  True],
       [False, False]])

In [30]:
mask = a ==4
print(a[mask])

[4]


In [31]:
mask = a < 4
mask

array([[ True,  True],
       [ True, False],
       [False, False]])

In [32]:
print(a[mask])

[1 2 3]


In [33]:
a = np.array([[1,2], [3,4], [5,6]])
mask = np.array([True, False, True])

print(a[mask])

[[1 2]
 [5 6]]


In [34]:
mask

array([ True, False,  True])

In [35]:
# Propertiese of NumPy

# Shape

arr = np.random.randint(low = 10, high = 50, size = (5,2,3))
arr

array([[[15, 30, 22],
        [23, 45, 37]],

       [[13, 12, 13],
        [43, 33, 29]],

       [[12, 35, 42],
        [13, 16, 28]],

       [[25, 10, 40],
        [19, 36, 16]],

       [[18, 21, 18],
        [39, 49, 43]]])

In [36]:
arr.shape

(5, 2, 3)

In [37]:
arr.dtype

dtype('int64')

In [38]:
arr.ndim # (shows the dimension)

3

In [39]:
# Transpose

arr.T

array([[[15, 13, 12, 25, 18],
        [23, 43, 13, 19, 39]],

       [[30, 12, 35, 10, 21],
        [45, 33, 16, 36, 49]],

       [[22, 13, 42, 40, 18],
        [37, 29, 28, 16, 43]]])

In [40]:
arr.T.shape

(3, 2, 5)

## Method of NumPy

In [41]:
# reshape

arr.reshape(5,2,3)

array([[[15, 30, 22],
        [23, 45, 37]],

       [[13, 12, 13],
        [43, 33, 29]],

       [[12, 35, 42],
        [13, 16, 28]],

       [[25, 10, 40],
        [19, 36, 16]],

       [[18, 21, 18],
        [39, 49, 43]]])

In [42]:
new_arr = arr.reshape(3,5,2)
new_arr

array([[[15, 30],
        [22, 23],
        [45, 37],
        [13, 12],
        [13, 43]],

       [[33, 29],
        [12, 35],
        [42, 13],
        [16, 28],
        [25, 10]],

       [[40, 19],
        [36, 16],
        [18, 21],
        [18, 39],
        [49, 43]]])

In [43]:
new_arr.shape

(3, 5, 2)

In [44]:
# ravel()
new_arr.ravel() # Throws all elements of dimension in 1 dimension or one array

array([15, 30, 22, 23, 45, 37, 13, 12, 13, 43, 33, 29, 12, 35, 42, 13, 16,
       28, 25, 10, 40, 19, 36, 16, 18, 21, 18, 39, 49, 43])

In [45]:
new_arr.shape

(3, 5, 2)

In [46]:
# flatten()

flat_arr = new_arr.flatten()
flat_arr

array([15, 30, 22, 23, 45, 37, 13, 12, 13, 43, 33, 29, 12, 35, 42, 13, 16,
       28, 25, 10, 40, 19, 36, 16, 18, 21, 18, 39, 49, 43])

In [47]:
flat_arr.shape

(30,)

In [48]:
arr.shape

(5, 2, 3)

In [49]:
# sum()

arr.sum(axis = 1)  # 1 means row and 0 means column in axis

array([[38, 75, 59],
       [56, 45, 42],
       [25, 51, 70],
       [44, 46, 56],
       [57, 70, 61]])

In [50]:
arr

array([[[15, 30, 22],
        [23, 45, 37]],

       [[13, 12, 13],
        [43, 33, 29]],

       [[12, 35, 42],
        [13, 16, 28]],

       [[25, 10, 40],
        [19, 36, 16]],

       [[18, 21, 18],
        [39, 49, 43]]])

In [51]:
arr.sum(axis = 0)

array([[ 83, 108, 135],
       [137, 179, 153]])

In [52]:

arr.prod(axis = 1)

array([[ 345, 1350,  814],
       [ 559,  396,  377],
       [ 156,  560, 1176],
       [ 475,  360,  640],
       [ 702, 1029,  774]])

In [53]:
arr.argmax(axis = 1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 1, 1]])