## Indexing-and-slicing

In [1]:
import numpy as np

In [2]:
np.random.randint(-10,10,10)

array([-3,  6, -6, -5,  7,  2,  0, -3,  0,  6])

In [9]:
# 1D Array -> Similar to List/Vector

array = np.array([1,5,3,7])

In [10]:
array[0]

np.int64(1)

In [11]:
print(array[0])

1


In [12]:
print(array[1::2])

[5 7]


In [31]:
# 2D -> Similar to matrix 
list2 = [[2,5,7,6], [4,9,11,23],[6,7,34,2],[12,5,2,8]]
array2 = np.array(list2)
array2

array([[ 2,  5,  7,  6],
       [ 4,  9, 11, 23],
       [ 6,  7, 34,  2],
       [12,  5,  2,  8]])

In [32]:
array2[0][2]

np.int64(7)

In [41]:
#array2[rows, columns]

array2[0:3, 0:3]

array([[ 2,  5,  7],
       [ 4,  9, 11],
       [ 6,  7, 34]])

In [42]:
array2[::2,]

array([[ 2,  5,  7,  6],
       [ 6,  7, 34,  2]])

In [43]:
array2.ndim

2

In [44]:
array2[::,]

array([[ 2,  5,  7,  6],
       [ 4,  9, 11, 23],
       [ 6,  7, 34,  2],
       [12,  5,  2,  8]])

In [45]:
array2.ndim

2

In [46]:
array2.shape

(4, 4)

In [47]:
random_array = np.random.randint(10,50, size = (2,3,4))

In [48]:
# Indexing 
random_array

array([[[40, 35, 30, 12],
        [25, 31, 11, 35],
        [36, 17, 34, 25]],

       [[49, 30, 49, 15],
        [38, 16, 23, 11],
        [28, 33, 42, 11]]])

In [51]:
print(random_array[0, 2, 2])

34


In [54]:
print(random_array[0, :2, :2])

[[40 35]
 [25 31]]


In [55]:
print(random_array[::2, :3, :4])

[[[40 35 30 12]
  [25 31 11 35]
  [36 17 34 25]]]


In [56]:
random_array

array([[[40, 35, 30, 12],
        [25, 31, 11, 35],
        [36, 17, 34, 25]],

       [[49, 30, 49, 15],
        [38, 16, 23, 11],
        [28, 33, 42, 11]]])

In [64]:
print(random_array[-1, :-2, :4])

[[49 30 49 15]]


In [65]:
random_array1 = np.random.randint(low = 10, high = 50, size = (10,16,8))

In [66]:
random_array1

array([[[12, 36, 23, ..., 11, 28, 41],
        [24, 37, 16, ..., 42, 22, 20],
        [26, 40, 11, ..., 31, 32, 19],
        ...,
        [17, 14, 29, ..., 30, 34, 14],
        [29, 48, 41, ..., 17, 16, 32],
        [49, 24, 45, ..., 41, 29, 18]],

       [[44, 42, 15, ..., 46, 42, 26],
        [43, 43, 32, ..., 26, 40, 45],
        [39, 29, 31, ..., 49, 40, 31],
        ...,
        [41, 34, 21, ..., 27, 43, 26],
        [30, 42, 12, ..., 37, 11, 35],
        [47, 10, 17, ..., 30, 29, 13]],

       [[16, 13, 39, ..., 23, 29, 37],
        [40, 25, 41, ..., 40, 20, 13],
        [27, 29, 45, ..., 37, 17, 12],
        ...,
        [32, 14, 44, ..., 20, 17, 18],
        [27, 11, 45, ..., 48, 43, 15],
        [11, 21, 13, ..., 34, 17, 47]],

       ...,

       [[17, 16, 41, ..., 29, 14, 35],
        [26, 48, 22, ..., 43, 10, 15],
        [41, 46, 46, ..., 26, 27, 25],
        ...,
        [30, 43, 43, ..., 13, 23, 35],
        [19, 20, 30, ..., 20, 28, 34],
        [30, 47, 16, ..., 30, 40

In [67]:
print(random_array1[4, :4, :9])

[[30 31 20 30 37 47 37 38]
 [32 21 36 15 22 34 10 44]
 [36 12 47 20 37 39 42 33]
 [35 23 14 21 48 17 20 31]]


In [68]:
print(random_array1[4, :4, -2: ])

[[37 38]
 [10 44]
 [42 33]
 [20 31]]


## Boolean or Mask Indexing

In [71]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [74]:
a == 4

array([[False, False],
       [False,  True],
       [False, False]])

In [77]:
mask = a ==4
print(a[mask])

[4]


In [80]:
mask = a < 4
mask

array([[ True,  True],
       [ True, False],
       [False, False]])

In [79]:
print(a[mask])

[1 2 3]


In [86]:
a = np.array([[1,2], [3,4], [5,6]])
mask = np.array([True, False, True])

print(a[mask])

[[1 2]
 [5 6]]


In [87]:
mask

array([ True, False,  True])

In [88]:
# Propertiese of NumPy

# Shape

arr = np.random.randint(low = 10, high = 50, size = (5,2,3))
arr

array([[[49, 43, 30],
        [38, 17, 23]],

       [[14, 28, 44],
        [29, 13, 46]],

       [[42, 10, 13],
        [38, 13, 12]],

       [[21, 10, 48],
        [43, 47, 40]],

       [[33, 44, 33],
        [49, 42, 18]]])

In [89]:
arr.shape

(5, 2, 3)

In [90]:
arr.dtype

dtype('int64')

In [91]:
arr.ndim # (shows the dimension)

3

In [92]:
# Transpose

arr.T

array([[[49, 14, 42, 21, 33],
        [38, 29, 38, 43, 49]],

       [[43, 28, 10, 10, 44],
        [17, 13, 13, 47, 42]],

       [[30, 44, 13, 48, 33],
        [23, 46, 12, 40, 18]]])

In [94]:
arr.T.shape

(3, 2, 5)

## Method of NumPy

In [95]:
# reshape

arr.reshape(5,2,3)

array([[[49, 43, 30],
        [38, 17, 23]],

       [[14, 28, 44],
        [29, 13, 46]],

       [[42, 10, 13],
        [38, 13, 12]],

       [[21, 10, 48],
        [43, 47, 40]],

       [[33, 44, 33],
        [49, 42, 18]]])

In [104]:
new_arr = arr.reshape(3,5,2)
new_arr

array([[[49, 43],
        [30, 38],
        [17, 23],
        [14, 28],
        [44, 29]],

       [[13, 46],
        [42, 10],
        [13, 38],
        [13, 12],
        [21, 10]],

       [[48, 43],
        [47, 40],
        [33, 44],
        [33, 49],
        [42, 18]]])

In [105]:
new_arr.shape

(3, 5, 2)

In [111]:
# ravel()
new_arr.ravel() # Throws all elements of dimension in 1 dimension or one array

array([49, 43, 30, 38, 17, 23, 14, 28, 44, 29, 13, 46, 42, 10, 13, 38, 13,
       12, 21, 10, 48, 43, 47, 40, 33, 44, 33, 49, 42, 18])

In [110]:
new_arr.shape

(3, 5, 2)

In [114]:
# flatten()

flat_arr = new_arr.flatten()
flat_arr

array([49, 43, 30, 38, 17, 23, 14, 28, 44, 29, 13, 46, 42, 10, 13, 38, 13,
       12, 21, 10, 48, 43, 47, 40, 33, 44, 33, 49, 42, 18])

In [115]:
flat_arr.shape

(30,)

In [118]:
arr.shape

(5, 2, 3)

In [120]:
# sum()

arr.sum(axis = 1)  # 1 means row and 0 means column in axis

array([[87, 60, 53],
       [43, 41, 90],
       [80, 23, 25],
       [64, 57, 88],
       [82, 86, 51]])

In [117]:
arr

array([[[49, 43, 30],
        [38, 17, 23]],

       [[14, 28, 44],
        [29, 13, 46]],

       [[42, 10, 13],
        [38, 13, 12]],

       [[21, 10, 48],
        [43, 47, 40]],

       [[33, 44, 33],
        [49, 42, 18]]])

In [119]:
arr.sum(axis = 0)

array([[159, 135, 168],
       [197, 132, 139]])

In [121]:

arr.prod(axis = 1)

array([[1862,  731,  690],
       [ 406,  364, 2024],
       [1596,  130,  156],
       [ 903,  470, 1920],
       [1617, 1848,  594]])

In [122]:
arr.argmax()

np.int64(0)