In [1]:
!pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 551.6 kB/s eta 0:00:00 kB/s eta 0:00:01:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 1.2 MB/s eta 0:00:00m eta 0:00:010:00:010m


In [4]:
import numpy as np

#list

list1 = [11,12,4]
list((12,12,3,1))


[12, 12, 3, 1]

In [6]:
# numpy array

array = np.array([1,4,7])
array

array([1, 4, 7])

In [7]:
type(array)

numpy.ndarray

In [10]:
print(array.shape)

(3,)


In [11]:
print(array.ndim)

1


In [13]:
list2 = [[12,2,3],
         [23,12,42]]

array2 = np.array(list2)

In [14]:
print(array2)
print(array2.ndim)
print(array2.shape)

[[12  2  3]
 [23 12 42]]
2
(2, 3)


In [34]:
array2.dtype

dtype('int64')

#### numpy takes 1 vector or 1 array as 1 dimension 

## Zeros matrix

In [16]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [19]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Ones Matrix

In [20]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [21]:
print(np.ones((5,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Identity matrix

In [47]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Random Matrix

In [35]:
print(np.random.rand(2,3))

[[0.73230097 0.38666672 0.19492481]
 [0.72452537 0.4892127  0.94220368]]


In [37]:
list(range(5,55,5))

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [38]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [39]:
np.arange(-6.4,15.5,2.12)

array([-6.4 , -4.28, -2.16, -0.04,  2.08,  4.2 ,  6.32,  8.44, 10.56,
       12.68, 14.8 ])

In [42]:
# np.linspace(start, stop, no_element) > linear space

array_linspace1 = np.linspace(start = 0, stop = 10, num = 5)
print(array_linspace1)

[ 0.   2.5  5.   7.5 10. ]


In [43]:
array_linspace2 = np.linspace(start = (0,0,0),stop = (10,20,30), num=5, axis = 1) # Axis = 1 means start with 
print(array_linspace2)

[[ 0.   2.5  5.   7.5 10. ]
 [ 0.   5.  10.  15.  20. ]
 [ 0.   7.5 15.  22.5 30. ]]


In [44]:
array_linspace2 = np.linspace(start = (0,0,0),stop = (10,20,30), num=5, axis = 0) # Axis = 0 means complete 1 rows and while making multiple column
print(array_linspace2)

[[ 0.   0.   0. ]
 [ 2.5  5.   7.5]
 [ 5.  10.  15. ]
 [ 7.5 15.  22.5]
 [10.  20.  30. ]]


In [46]:
np.eye(5,4) # np.eye doesn't take tuple as input

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [49]:
np.diag([3,6,3,6])

array([[3, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 6]])

In [54]:
np.random.randint(low = 0, high = 10,size = (2,3,4)) # size = (2,3,4P) means 2 matrices of 3X4

array([[[5, 2, 1, 2],
        [8, 8, 9, 3],
        [1, 7, 6, 2]],

       [[1, 3, 8, 6],
        [9, 4, 0, 9],
        [2, 4, 1, 1]]])

In [62]:
# Generating a 4D array with random integers between 0 and 9 (high=10 is exclusive)

nDarray = np.random.randint(low = 0, high = 10,size = (2,3,4,5)) 

# Explanation of size=(2, 2, 3, 4):
# This creates a 4D array, where:
# - The outermost level has 2 blocks (first 2 in size tuple) --> shape: (2)
# - Each block contains 2 matrices (second 2 in size tuple) --> shape: (2, 2)
# - Each matrix has 3 rows (third 3 in size tuple) --> shape: (2, 2, 3)
# - Each row has 4 columns (fourth 4 in size tuple) --> shape: (2, 2, 3, 4)
#
# Overall, this generates a 4D array with the shape (2, 2, 3, 4).
# For example, you can think of it as:
# - 2 blocks
# - Each block has 2 matrices
# - Each matrix has 3 rows and 4 columns of random integers

nDarray

array([[[[6, 7, 8, 6, 7],
         [6, 7, 6, 0, 0],
         [1, 4, 3, 8, 5],
         [3, 6, 7, 1, 9]],

        [[4, 3, 0, 8, 8],
         [7, 1, 6, 4, 5],
         [7, 8, 0, 1, 0],
         [1, 1, 5, 3, 2]],

        [[0, 0, 6, 1, 0],
         [3, 8, 7, 1, 7],
         [6, 0, 9, 8, 9],
         [4, 4, 1, 5, 2]]],


       [[[8, 1, 2, 0, 3],
         [1, 6, 6, 5, 7],
         [0, 4, 9, 1, 0],
         [2, 9, 6, 2, 1]],

        [[0, 1, 4, 3, 1],
         [8, 5, 2, 7, 2],
         [9, 2, 6, 9, 4],
         [3, 0, 8, 7, 1]],

        [[9, 6, 2, 1, 6],
         [7, 6, 5, 3, 4],
         [2, 5, 7, 7, 3],
         [5, 4, 3, 3, 6]]]])

In [61]:
nDarray.shape

(2, 2, 3, 4)